version: '3.8'

services:
  portfolio-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./portfolio-site:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped

  # 開発用サービス（オプション）
  portfolio-dev:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./portfolio-site:/app
      - /app/node_modules
    command: npm run dev
    profiles:
      - dev 